### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by razon30** [mSvcBench/muBench#21]
I am getting the follwoing error with "python3 Deployers/K8sDeployer/RunK8sDeployer.py -c Configs/K8sParameters.json"
I am using windows 10.

######################
We are going to DEPLOY the yaml files in the following folder: SimulationWorkspace/yamls
######################
Traceback (most recent call last):
  File "Deployers/K8sDeployer/RunK8sDeployer.py", line 117, in <module>
    K8sYamlDeployer.deploy_items(folder, st=k8s_parameters['sleep'])
  File "/root/muBench/Deployers/K8sDeployer/K8sYamlDeployer.py", line 13, in deploy_items
    config.load_kube_config()
  File "/usr/local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 813, in load_kube_config
    loader = _get_kube_config_loader(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 767, in _get_kube_config_loader
    kcfg = KubeConfigMerger(filename)
  File "/usr/local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 686, in __init__
    self._load_config_from_file_path(paths)
  File "/usr/local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 711, in _load_config_from_file_path
    self.load_config(path)
  File "/usr/local/lib/python3.8/site-packages/kubernetes/config/kube_config.py", line 716, in load_config
    config = yaml.safe_load(f)
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.8/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/local/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by andreadetti** [comment]
It seems that config.load_kube_config() has problem with win10. Do you have kubectl access to the kubernetes cluster?
